language: android
jdk: oraclejdk8

env:
   global:
      -ANDROID_API_LEVEL=27
      -ANDROID_BUILD_TOOLS_VERSION=27.0.3
android:
   licenses:
   - android-sdk-preview-license-.+
   - android-sdk-license-.+
   - google-gdk-license-.+
   components:
   - tools
   - build-tools-$ANDROID_BUILD_TOOLS_VERSION
   - platform-tools
   - android-$ANDROID_API_LEVEL

   - extra-google-google_play_services
   - extra-google-m2repository
   - extra-android-m2repository
   - addon-google_apis-google-$ANDROID_API_LEVEL

sudo: required
dist: bionic

before_install:
- chmod +x ./gradlew
- chmod +x gradlew
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
- ./gradlew check


