language: android
jdk: oraclejdk8

env:
   global:
      -ANDROID_API_LEVEL=25
      -ANDROID_BUILD_TOOLS_VERSION=25.0.2
android:
   licenses:
   - 'android-sdk-preview-license-.+'
   - 'android-sdk-license-.+'
   - 'google-gdk-license-.+'
   components:
   - tools
   - build-tools-$ANDROID_BUILD_TOOLS_VERSION=25.0.2
   - platform-tools
   - android-$ANDROID_API_LEVEL

   - extra-google-google_play_services
   - extra-google-m2repository
   - extra-android-m2repository
   - addon-google_apis-google-$ANDROID_API_LEVEL

sudo: required
dist: trusty

before_install:
- sudo chmod +x ./gradlew

script:
- javac -d Tetris/ Tetris/*.java
- ./gradlew check


